# main config file
output_dir: results
sub_dir: none
defaults:
  - datasource: nexrad
  - model: FluxRGNN
  - task: train_eval
  - device: local
  - logger: wandb
job_id: 0
season: fall
seed: 1234
model_seed: ${seed}
root_transform: 0
missing_data_threshold: 0.1
t_unit: 1H
fixed_t0: false
data_perc: 1.0
exclude: []
verbose: True
debugging: False

# lightning trainer setup
trainer:
  _target_: pytorch_lightning.Trainer
  logger: ${logger}
  log_every_n_steps: 10
  callbacks:
    - _target_: callbacks.PredictionCallback
    - _target_: pytorch_lightning.callbacks.LearningRateMonitor
#    - _target_: callbacks.ReconstructionCallback
  accelerator: ${device.accelerator}
  devices: ${device.devices}
  deterministic: True
  gradient_clip_algorithm: value
  gradient_clip_val: 0
  max_epochs: 10

dataloader:
  _target_: torch_geometric.data.DataLoader
  batch_size: 4
  shuffle: True
