# main config file
output_dir: results
sub_dir: none
defaults:
  - datasource: nexrad
  - model: FluxRGNN
  - task: train_eval
  - device: cluster
  - logger: wandb
job_id: 0
season: fall
seed: 1234
model_seed: ${seed}
root_transform: 0
missing_data_threshold: 0.1
t_unit: 1H
fixed_t0: false
data_perc: 1.0
exclude: []
verbose: True
debugging: False

# lightning trainer setup
trainer:
  _target_: pytorch_lightning.Trainer
  logger: ${logger}
  log_every_n_steps: 1
  callbacks:
    - _target_: pytorch_lightning.callbacks.LearningRateMonitor
      #- _target_: pytorch_lightning.callbacks.EarlyStopping
      #monitor: val/loss
      #patience: 10
    - _target_: callbacks.GradNormCallback
    - _target_: callbacks.PredictionCallback
  accelerator: ${device.accelerator}
  devices: ${device.devices}
  deterministic: True
  gradient_clip_algorithm: value
  gradient_clip_val: 0
  max_epochs: 20
  # for debugging
#  overfit_batches: 10
#  track_grad_norm: 2
  fast_dev_run: false
  enable_model_summary: true

dataloader:
  _target_: torch_geometric.data.DataLoader
  batch_size: 128
  shuffle: True
