# @package model.initial_model
_target_: fluxrgnn.models.CorrectedRadarToCellKNNInterpolation
_partial_: true
k: 10
radar_variables:
  x: 1
static_cell_features:
  coords: ${model.coord_dim}
dynamic_cell_features: ${model.env_vars}
n_hidden: ${model.radar2cell_n_hidden}
n_fc_layers: ${model.radar2cell_n_layers}
activation: ${model.activation}
dropout_p: ${model.dropout_p}
