# @package model.initial_model
_target_: fluxrgnn.models.InitialStateMLP
node_features:
  coords: ${model.coord_dim}
dynamic_cell_features: ${model.env_vars}
static_cell_features:
  coords: ${model.coord_dim}
n_hidden: ${model.n_hidden}
n_fc_layers: 1
activation:
  _target_: torch.nn.ReLU
use_log_transform: ${model.use_log_transform}
dropout_p: ${model.dropout_p}
transforms: ${model.transforms}
