# @package model.flux_model
# directly predict fluxes between cells
_target_: fluxrgnn.models.Fluxes
edge_features:
  edge_attr: ${model.n_edge_attr}
dynamic_cell_features: ${model.env_vars}
n_hidden: ${model.n_hidden}
n_fc_layers: 1
n_graph_layers: 0
activation: ${model.activation}
use_log_transform: ${model.use_log_transform}
dropout_p: ${model.dropout_p}
transforms: ${model.transforms}
