name: fluxrgnn
channels:
  - pytorch
  - pyg
  - conda-forge
  - nvidia
dependencies:
  - python>=3.9
  - pip
  - numpy
  - scipy
  - networkx
  - torchvision
  - torchaudio
  - cudatoolkit
  - pytorch=2.0
  - pytorch-cuda
  - pytorch-lightning
  - pyg
  - scikit-learn
  - pygam
  - yaml
  - hydra-core>=1.1
  - wandb
  - pandas
  - matplotlib
  - pip:
    - torch-geometric-temporal
