name: fluxrgnn
channels:
  - pytorch
  - pyg
  - anaconda
  - conda-forge
dependencies:
   - python=3.8.3
   - pip
   - numpy
   - scipy
   - networkx
   - torchvision
   - cudatoolkit=10.2
   - pytorch
   - pyg
   - scikit-learn
   - pygam
   - ruamel.yaml
   - yaml
   - hydra-core
   - pandas
   - matplotlib
   - seaborn
     #- pip:
     #      - hydra-core
   # - geopandas
   # - cartopy
   # - geoplot
   # - shapely

