name: fluxrgnn
channels:
  - pytorch
  - pyg
  - anaconda
  - conda-forge
  - nvidia
dependencies:
<<<<<<< HEAD
   - python>=3.8
   - numpy
   - scipy
   - networkx
   - pytorch
   - torchvision
   - torchaudio
   - torch-cuda
   - cudatoolkit
=======
   - python=3.9
   - numpy
   - scipy
   - networkx
   - torchvision
   - torchaudio
   - cudatoolkit
   - pytorch=2.0
   - pytorch-cuda
>>>>>>> f775254d786662eb6514fb5e8e6759e8cbff1692
   - pytorch-lightning
   - pyg
   - scikit-learn
   - pygam
<<<<<<< HEAD
#   - ruamel.yaml
=======
>>>>>>> f775254d786662eb6514fb5e8e6759e8cbff1692
   - yaml
   - hydra-core
   - wandb
   - pandas
   - matplotlib
     #- notebook
     #- seaborn
     #- geopandas
     #- cartopy
     #- geoplot
     #- shapely

