name: fluxrgnn
channels:
  - pytorch
  - pyg
  - anaconda
  - conda-forge
  - nvidia
dependencies:
  - python=3.9
  - pip
  - numpy
  - scipy
  - networkx
  - torchvision
  - torchaudio
  - cudatoolkit
  - pytorch=2.0
  - pytorch-cuda
  - pytorch-lightning
  - pyg
  - scikit-learn
  - pygam
  - yaml
  - hydra-core
  - wandb
  - pandas
  - matplotlib
  - ipykernel
  - pip:
    - torch-geometric-temporal
  #- notebook
  #- seaborn
  #- geopandas
  #- cartopy
  #- geoplot
  #- shapely

