name: fluxrgnn
channels:
  - pytorch
  - pyg
  - anaconda
  - conda-forge
dependencies:
   - python=3.8.3
   - numpy
   - scipy
   - networkx
   - torchvision
   - cudatoolkit=10.2
   - pytorch
   - pyg
   - sklearn
   - pygam
   - omegaconf
   - hydra-core
   - ruamel
   - yaml
   - pickle
   - pandas
   - matplotlib
   - seaborn
   # - geopandas
   # - cartopy
   # - geoplot
   # - shapely

