# @package _group_
name: AttentionGraphLSTM
hyperparameters:
  n_hidden:
    default: 64
    search_space:
    - 64
    - 128
  n_lstm_layers:
    default: 1
    search_space:
    - 1
  dropout_p:
    default: 0.25
    search_space:
    - 0.25
  lr:
    default: 0.001
    search_space:
      - 0.001
      - 0.0001
      - 0.00001
  lr_decay:
    default: 50
    search_space:
    - 50
  teacher_forcing_gamma:
    default: 0.9
    search_space:
    - 0.9
  predict_delta:
    default: True
    search_space:
      - True
      - False
epochs: 100
horizon: 40
fixed_boundary: false
force_zeros: false
use_encoder: false
encoder_type: temporal
context: 0
root_transformed_loss: false
batch_size: 1
