# @package model
_target_: fluxrgnn.models.FluxRGNN

name: FluxRGNN+

coord_dim: 4
embedding_dim: 32
radar_embedding_dim: 8
radar2cell_n_hidden: 16
radar2cell_n_layers: 1
n_edge_attr: 6

training_coefs:
  x: 1.0
  bird_uv: 0.1
test_vars:
  - x
  - bird_uv
predict_vars:
  - x
  - bird_uv
  - in_flux
  - out_flux
  - source_sink

env_vars:
  u_q10: 1
  u_q50: 1
  u_q90: 1
  v_q10: 1
  v_q50: 1
  v_q90: 1
  tcc: 1
  tp: 1
  sp: 1
  msl: 1
  t_q10: 1
  t_q50: 1
  t_q90: 1
  q_q10: 1
  q_q50: 1
  q_q90: 1
  night: 1
  dusk: 1
  dawn: 1
  dayofyear: 1
  solarpos: 1
  solarpos_dt: 1

permute_env_vars: []

n_hidden: 128 

max_t0: ${datasource.tidx_step}
max_t0_test: 1
context: 24
horizon: 48
min_horizon: 2
test_horizon: 72

store_fluxes: false

lr: 1e-4
lr_decay: 1.0
lr_schedulers:
        - _target_: torch.optim.lr_scheduler.CosineAnnealingLR
          _partial_: true
          T_max: ${trainer.max_epochs}
          eta_min: ${eval:'${model.lr} * ${model.lr_decay}'} 
lr_milestones: []
optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: ${model.lr}

use_log_transform: false # if true, model log-transformed bird densities
log_offset: 0.1
scale: 0.001 # (roughly 1/99.9 percentile for night-time bird densities in fall)
# scale: 0.002 (roughly 1/99.9 percentile for night-time bird densities in spring)
length_scale: 0.01 # (roughly 1/99.9 percentile of absolute uv during night time)
flux_scale: ${eval:'${model.scale} * ${model.length_scale}'} #0.00001
transforms:
#  - _target_: fluxrgnn.transforms.LogTransform
#    feature: x
#    offset: ${model.log_offset}
  - _target_: fluxrgnn.transforms.Rescaling
    feature: x
    factor: ${model.scale}
  - _target_: fluxrgnn.transforms.Rescaling
    feature: bird_uv
    factor: ${model.length_scale}
  - _target_: fluxrgnn.transforms.Rescaling
    feature: in_flux
    factor: ${model.scale}
  - _target_: fluxrgnn.transforms.Rescaling
    feature: out_flux
    factor: ${model.scale}
  - _target_: fluxrgnn.transforms.Rescaling
    feature: source_sink
    factor: ${model.scale}
  - _target_: fluxrgnn.transforms.CVMasks
    n_cv_folds: ${task.n_cv_folds}
    cv_fold: ${task.cv_fold}
    seed: ${seed}

dropout_p: 0.1
teacher_forcing: 0.0
teacher_forcing_gamma: 1.0 # decay rate of teacher forcing
increase_horizon_rate: 0.1 # rate at which forecast horizon is increased during training
increase_horizon_start: 0


force_zeros: false # if true, set bird densities during the day to zero
root_transformed_loss: false
weight_exponent: 1.0
edge_type: hexagons
birds_per_km2: true

regularizer_weight: 0.0

activation:
  _target_: torch.nn.ReLU #LeakyReLU

observation_model:
  _target_: fluxrgnn.models.ObservationModel

node_rnn:
  _target_: fluxrgnn.models.NodeLSTM
  _partial_: true

boundary_model:
  _target_: fluxrgnn.models.Extrapolation

defaults:
  - flux_model: NumericalFluxes
  - source_sink_model: SourceSink
  - location_encoder: LocationEncoder
  - encoder: RecurrentEncoder
  - decoder: RecurrentDecoder
  - radar2cell_model: KNNInterpolation #KNNInterpolation
  - initial_model: KNNInterpolation #KNNInterpolation


load_states_from: null
