# @package model
_target_: fluxrgnn.models.FluxRGNN

name: FluxRGNN

coord_dim: 4
n_edge_attr: 5
n_env: ${len:${datasource.env_vars}}

n_hidden: 64

max_t0: ${datasource.tidx_step}
context: 24
horizon: 48
min_horizon: 2
test_horizon: 72

lr: 1e-5
lr_schedulers:
        - _target_: torch.optim.lr_scheduler.ConstantLR
          _partial_: true
          factor: 1.0
          total_iters: ${trainer.max_epochs}
lr_milestones: []

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: ${model.lr}

use_log_transform: false
log_offset: 0.1
scale: 0.001
transforms:
  - _target_: transforms.Rescaling
    feature: x
    factor: ${model.scale}

dropout_p: 0.0
teacher_forcing: 0.0
teacher_forcing_gamma: 0.95
increase_horizon_rate: 0.1
increase_horizon_start: 0

force_zeros: true
root_transformed_loss: false
edge_type: hexagons
birds_per_km2: true

regularizer_weight: 0.0

observation_model:
  _target_: fluxrgnn.models.ObservationModel

decoder:
  _target_: fluxrgnn.models.RecurrentDecoder
  n_hidden: ${model.n_hidden}
  n_lstm_layers: 1
  dropout_p: ${model.dropout_p}
  static_cell_features:
    coords: ${model.coord_dim}
  edge_features:
    edge_attr: ${model.n_edge_attr}
  dynamic_cell_features:
    env: ${model.n_env}

flux_model:
  _target_: fluxrgnn.models.Fluxes
  #_target_: fluxrgnn.models.NumericalFluxes
  static_cell_features:
    coords: ${model.coord_dim}
  edge_features:
    edge_attr: ${model.n_edge_attr}
  dynamic_cell_features:
    env: ${model.n_env}
  n_hidden: ${model.n_hidden}
  n_fc_layers: 2
  n_graph_layers: 0
  activation:
    _target_: torch.nn.ReLU
  use_log_transform: ${model.use_log_transform}
  log_offset: ${model.log_offset}
  scale: ${model.scale}
  dropout_p: ${model.dropout_p}
  transforms: ${model.transforms}


source_sink_model:
  _target_: fluxrgnn.models.SourceSink
  #_target_: fluxrgnn.models.DeltaMLP
  static_cell_features:
    coords: ${model.coord_dim}
  dynamic_cell_features:
    env: ${model.n_env}
  n_hidden: ${model.n_hidden}
  n_fc_layers: 1
  activation:
    _target_: torch.nn.ReLU # LeakyReLU
  use_log_transform: ${model.use_log_transform}
  log_offset: ${model.log_offset}
  scale: ${model.scale}
  dropout_p: ${model.dropout_p}
  transforms: ${model.transforms}


#initial_model:
#  _target_: fluxrgnn.models.InitialStateMLP
#  static_cell_features:
#    coords: ${model.coord_dim}
#  dynamic_cell_features:
#    env: ${model.n_env}
#  n_hidden: ${model.n_hidden}
#  n_fc_layers: 1
#  activation:
#    _target_: torch.nn.ReLU
#  use_log_transform: ${model.use_log_transform}
#  log_offset: ${model.log_offset}
#  scale: ${model.scale}
#  dropout_p: ${model.dropout_p}
#  transforms: ${model.transforms}

initial_model:
  _target_: fluxrgnn.models.RadarToCellInterpolation
  dynamic_radar_features:
    x: 1

encoder:
  _target_: fluxrgnn.models.RecurrentEncoder
  context: ${model.context}
  n_hidden: ${model.n_hidden}
  n_lstm_layers: 1
  dropout_p: ${model.dropout_p}
  radar2cell_model:
    _target_: fluxrgnn.models.RadarToCellInterpolation
    dynamic_radar_features:
      x: 1
      bird_uv: 2
  static_cell_features:
    coords: ${model.coord_dim}
  dynamic_cell_features:
    env: ${model.n_env}

boundary_model:
  _target_: fluxrgnn.models.Extrapolation

load_states_from: none
