# @package model
_target_: fluxrgnn.models.FluxRGNN

name: FluxRGNN

coord_dim: 2
n_edge_attr: 5
n_env: ${len:${datasource.env_vars}}

n_hidden: 128
#n_fc_layers: 2
#n_lstm_layers: 1
n_graph_layers: 0

context: 24
horizon: 24
test_horizon: 24

#epochs: 300
#batch_size: 4
lr: 1e-4
lr_decay: 300
lr_gamma: 1.0
#early_stopping: true
#stopping_criterion: 1e-6
#avg_window: 50
dropout_p: 0.0
teacher_forcing_gamma: 0.9

force_zeros: false
use_encoder: true
use_boundary_model: true
#use_uv: true
root_transformed_loss: false
compute_fluxes: true
edge_type: voronoi
birds_per_km2: true

use_log_transform: true
log_offset: 0.1
scale: 1.0

dynamics:
  _target_: fluxrgnn.models.FluxRGNNTransition
  n_hidden: ${model.n_hidden}
  n_fc_layers: 2
  n_lstm_layers: 1
  use_encoder: ${model.use_encoder}
  use_log_transform: ${model.use_log_transform}
  dropout_p: ${model.dropout_p}
  node_features:
    coords: ${model.coord_dim}
  edge_features:
    edge_attr: ${model.n_edge_attr}
  dynamic_features:
    env: ${model.n_env}

encoder:
  _target_: fluxrgnn.models.RecurrentEncoder
#  n_node_in: ${sum:[${model.n_env}, ${model.coord_dim}, 2]}
  context: ${model.context}
  n_hidden: ${model.n_hidden}
  n_lstm_layers: 1
  dropout_p: ${model.dropout_p}
  node_features:
    coords: ${model.coord_dim}
  dynamic_features:
    env: ${model.n_env}
    bird_uv: 2
    x: 1

boundary_model:
  _target_: fluxrgnn.models.Extrapolation

load_states_from: none
