# @package model
_target_: fluxrgnn.models.FluxRGNN

name: FluxRGNN

coord_dim: 2
n_edge_attr: 5
n_env: ${len:${datasource.env_vars}}

n_hidden: 128
#n_fc_layers: 2
#n_lstm_layers: 1

context: 24
horizon: 48
test_horizon: 72

lr: 1e-5
lr_decay: 300
lr_gamma: 1.0
dropout_p: 0.1
teacher_forcing_gamma: 1.0
increase_horizon: true

force_zeros: false
edge_type: hexagons 
birds_per_km2: true

use_log_transform: false
log_offset: 0.1
scale: 0.001

regularizer_weight: 0.0

observation_model:
  _target_: fluxrgnn.models.ObservationModel

decoder:
  _target_: fluxrgnn.models.RecurrentDecoder
  n_hidden: ${model.n_hidden}
  n_lstm_layers: 1
  dropout_p: ${model.dropout_p}
  node_features:
    coords: ${model.coord_dim}
  edge_features:
    edge_attr: ${model.n_edge_attr}
  dynamic_features:
    env: ${model.n_env}

flux_model:
  _target_: fluxrgnn.models.Fluxes
  node_features:
    coords: ${model.coord_dim}
  edge_features:
    edge_attr: ${model.n_edge_attr}
  dynamic_features:
    env: ${model.n_env}
  n_hidden: ${model.n_hidden}
  n_fc_layers: 2
  n_graph_layers: 0
  activation:
    _target_: torch.nn.ReLU
  use_log_transform: ${model.use_log_transform}
  log_offset: ${model.log_offset}
  scale: ${model.scale}
  dropout_p: ${model.dropout_p}


source_sink_model:
  _target_: fluxrgnn.models.SourceSink
  node_features:
    coords: ${model.coord_dim}
  dynamic_features:
    env: ${model.n_env}
  n_hidden: ${model.n_hidden}
  n_fc_layers: 1
  activation:
    _target_: torch.nn.LeakyReLU
  use_log_transform: ${model.use_log_transform}
  log_offset: ${model.log_offset}
  scale: ${model.scale}
  dropout_p: ${model.dropout_p}


#initial_model:
#  _target_: fluxrgnn.models.InitialStateMLP
#  node_features:
#    coords: ${model.coord_dim}
#  dynamic_features:
#    env: ${model.n_env}
#  n_hidden: ${model.n_hidden}
#  n_fc_layers: 1
#  activation:
#    _target_: torch.nn.ReLU
#  use_log_transform: ${model.use_log_transform}
#  log_offset: ${model.log_offset}
#  scale: ${model.scale}
#  dropout_p: ${model.dropout_p}


initial_model:
  _target_: fluxrgnn.models.RadarToCellInterpolation
  use_log_transform: ${model.use_log_transform}
  log_offset: ${model.log_offset}
  scale: ${model.scale}
  #mlp:
  #  _target_: fluxrgnn.models.MLP
  #  n_in: ${model.n_hidden} + 1
  #  n_out: 1
  #  n_fc_layers: 1
  #  activation:
  #    _target_: torch.nn.ReLU
  #  dropout_p: ${model.dropout_p}


encoder:
  _target_: fluxrgnn.models.RecurrentEncoder
  context: ${model.context}
  n_hidden: ${model.n_hidden}
  n_lstm_layers: 1
  dropout_p: ${model.dropout_p}
  node_features:
    coords: ${model.coord_dim}
  dynamic_features:
    env: ${model.n_env}
    #bird_uv: 2
    #x: 1

boundary_model:
  _target_: fluxrgnn.models.Extrapolation

load_states_from: none
