# @package model
_target_: fluxrgnn.models.FluxRGNN

name: FluxRGNN

n_hidden: 128
n_fc_layers: 2
n_lstm_layers: 1
n_graph_layers: 0

context: 24
horizon: 48
test_horizon: 72

epochs: 300
batch_size: 4
lr: 1e-5
lr_decay: 300
lr_gamma: 1.0
early_stopping: true
stopping_criterion: 1e-6
avg_window: 50
dropout_p: 0.25
teacher_forcing_gamma: 0.95

force_zeros: false
use_encoder: true
use_boundary_model: true
use_uv: true
root_transformed_loss: false
compute_fluxes: true
edge_type: voronoi
birds_per_km2: true
coord_dim: 2
n_edge_attr: 5

load_states_from: none
