# @package _group_
name: FluxRGNN
n_hidden: 128
n_fc_layers: 2
n_lstm_layers: 1
n_graph_layers: 0
dropout_p: 0.25
lr: 1e-5
lr_decay: 500
lr_gamma: 1.0
teacher_forcing_gamma: 0.95
flux_loss_weight: 0.0
epochs: 500
horizon: 48
test_horizon: 64
#fixed_boundary: false
force_zeros: false
use_encoder: true
use_boundary_model: true
use_uv: true
context: 24
root_transformed_loss: false
compute_fluxes: true
batch_size: 4
boundary_model: Extrapolation
load_states_from: none
edge_type: voronoi
birds_per_km2: true
n_dummy_radars: 25
early_stopping: true
stopping_criterion: 1e-6
avg_window: 50
