# @package model
_target_: fluxrgnn.models.FluxRGNN

name: FluxRGNN w/o fluxes

coord_dim: 2
n_edge_attr: 5
n_env: ${len:${datasource.env_vars}}

n_hidden: 128
n_graph_layers: 0

context: 24
horizon: 48
test_horizon: 48

lr: 1e-4
lr_decay: 300
lr_gamma: 1.0
dropout_p: 0.0
teacher_forcing_gamma: 0.9

force_zeros: false
use_encoder: true
root_transformed_loss: false
compute_fluxes: true
edge_type: voronoi
birds_per_km2: true

dynamics:
  _target_: fluxrgnn.models.LSTMTransition
  n_hidden: ${model.n_hidden}
  n_fc_layers: 2
  n_lstm_layers: 1
  use_encoder: ${model.use_encoder}
  dropout_p: ${model.dropout_p}
  node_features:
    coords: ${model.coord_dim}
  edge_features:
    edge_attr: ${model.n_edge_attr}
  dynamic_features:
    env: ${model.n_env}

encoder:
  _target_: fluxrgnn.models.RecurrentEncoder
  n_node_in: ${sum:[${model.n_env}, ${model.coord_dim}, 2]}
  context: ${model.context}
  n_hidden: ${model.n_hidden}
  n_lstm_layers: 1
  dropout_p: ${model.dropout_p}
  use_uv: true


load_states_from: none
