# @package model
_target_: fluxrgnn.models.FluxRGNN

name: FluxRGNN

defaults:
  - flux_model: NNFluxes
  - source_sink_model: SourceSink
  - encoder: RecurrentEncoder
  - decoder: RecurrentDecoder
  - location_encoder: null
  - radar2cell_model: ObservationCopy
  - initial_model: ObservationCopy


coord_dim: 4
#embedding_dim: 32
#radar_embedding_dim: 8
n_edge_attr: 6

training_coefs:
  x: 1.0
test_vars:
  - x
predict_vars:
  - x
  - fluxes
  - source_sink

env_vars:
  u_q10: 1
  u_q50: 1
  u_q90: 1
  v_q10: 1
  v_q50: 1
  v_q90: 1
  u10: 1
  v10: 1
  tcc: 1
  tp: 1
  sp: 1
  msl: 1
  #t2m: 1
  t_q10: 1
  t_q50: 1
  t_q90: 1
  q_q10: 1
  q_q50: 1
  q_q90: 1
  #sshf: 1
  night: 1
  dusk: 1
  dawn: 1
  dayofyear: 1
  solarpos: 1
  solarpos_dt: 1
  #frac_night_fw: 1
  #frac_night_bw: 1

permute_env_vars: []

n_hidden: 128 

max_t0: ${datasource.tidx_step}
context: 24
horizon: 48
min_horizon: 2
test_horizon: 72

store_fluxes: false

lr: 3e-5
lr_schedulers:
        - _target_: torch.optim.lr_scheduler.ConstantLR
          _partial_: true
          factor: 1.0
          total_iters: ${trainer.max_epochs}
lr_milestones: []

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: ${model.lr}

use_log_transform: false
log_offset: 0.1
scale: 0.001
length_scale: 0.01
flux_scale: ${eval:'${model.scale} * ${model.length_scale}'}

transforms:
  - _target_: fluxrgnn.transforms.Rescaling
    feature: x
    factor: ${model.scale}
  - _target_: fluxrgnn.transforms.Rescaling
    feature: bird_uv
    factor: ${model.length_scale}
  - _target_: fluxrgnn.transforms.Rescaling
    feature: fluxes
    factor: ${model.flux_scale}
  - _target_: fluxrgnn.transforms.Rescaling
    feature: source_sink
    factor: ${model.scale}
  - _target_: fluxrgnn.transforms.CVMasks
    n_cv_folds: ${task.n_cv_folds}
    cv_fold: ${task.cv_fold}
    seed: ${seed}

dropout_p: 0.0
teacher_forcing: 0.0
teacher_forcing_gamma: 1.0
increase_horizon_rate: 0.1
increase_horizon_start: 0


force_zeros: false #true
root_transformed_loss: false
weight_exponent: 1.0 #0.75
edge_type: voronoi
birds_per_km2: true

regularizer_weight: 0.0 #0.01

activation:
  _target_: torch.nn.ReLU #LeakyReLU

observation_model:
  _target_: fluxrgnn.models.ObservationModel

node_rnn:
  _target_: fluxrgnn.models.NodeLSTM
  _partial_: true

boundary_model:
  _target_: fluxrgnn.models.Extrapolation

load_states_from: null
