# @package _group_
name: GraphLSTM
hyperparameters:
  n_hidden:
    default: 128
    search_space:
    - 64
    - 128
  n_fc_layers:
    default: 2
    search_space:
      - 1
      - 2
  n_lstm_layers:
    default: 1
    search_space:
    - 1
  dropout_p:
    default: 0.25
    search_space:
    - 0.25
  lr:
    default: 0.001
    search_space:
      - 0.001
      - 0.0001
      - 0.00001
      - 0.000001
  lr_decay:
    default: 50
    search_space:
    - 50
  teacher_forcing_gamma:
    default: 0.9
    search_space:
    - 0.9
  predict_delta:
    default: true
    search_space:
    - true
epochs: 100
horizon: 40
context: 24
fixed_boundary: false
force_zeros: false
use_encoder: false
root_transformed_loss: true
batch_size: 1

