# @package model
_target_: fluxrgnn.models.LocalMLPForecast

name: LocalMLP

n_hidden: 256
n_fc_layers: 3
square_output: true

n_env: ${len:${datasource.env_vars}}
dropout_p: 0.0

lr: 1e-3
lr_schedulers:
        - _target_: torch.optim.lr_scheduler.ConstantLR
          _partial_: true
          factor: 1e-2
          total_iters: ${trainer.max_epochs}
lr_milestones: []

optimizer:
        _target_: torch.optim.Adam
        _partial_: true
        lr: ${model.lr}


use_log_transform: true
log_offset: 0.1
scale: 0.1
transforms:
  - _target_: transforms.LogTransform
    feature: x
    offset: ${model.log_offset}
  - _target_: transforms.Rescaling
    feature: x
    factor: ${model.scale}

increase_horizon_rate: 0.0
increase_horizon_start: 0
#lr_decay: 300
#lr_gamma: 1.0

max_t0: ${datasource.tidx_step}
horizon: 48
context: 24
test_horizon: 72
test_context: 24

force_zeros: false
use_acc_vars: false
root_transformed_loss: false
batch_size: 128
edge_type: none
birds_per_km2: true
n_dummy_radars: 0
early_stopping: true
stopping_criterion: 1e-6
avg_window: 10
coord_dim: 2
#n_edge_attr: 4


observation_model:
    _target_: fluxrgnn.models.ObservationModel
