# @package model
name: LocalLSTM

n_hidden: 64
n_lstm_layers: 1

context: 24
horizon: 48
test_horizon: 72

epochs: 300
batch_size: 8
lr: 3e-5
lr_decay: 300
lr_gamma: 1.0
early_stopping: true
stopping_criterion: 1e-6
avg_window: 50
dropout_p: 0.25
teacher_forcing_gamma: 0.95

predict_delta: true
force_zeros: false
use_encoder: true
use_uv: true
root_transformed_loss: false
edge_type: none
coord_dim: 2
n_edge_attr: 5 # or 4?

birds_per_km2: false

load_states_from: none




