# @package model
_target_: fluxrgnn.models.SeasonalForecast

name: Seasonality

context: 24
test_horizon: 72

edge_type: none
birds_per_km2: true

use_log_transform: true
log_offset: 0.1
scale: 1.0

load_states_from: none
