# @package _group_
name: testFluxMLP
hyperparameters:
  n_hidden:
    default: 64
    search_space:
    - 64
    - 128
  n_fc_layers:
    default: 2
    search_space:
      - 1
      - 2
  n_lstm_layers:
    default: 1
    search_space:
    - 1
  n_fc_layers_fluxmlp:
    default: 2
    search_space:
      - 1
      - 2
  n_hidden_fluxmlp:
    default: 64
    search_space:
      - 64
      - 128
  dropout_p:
    default: 0.25
    search_space:
    - 0.25
  lr:
    default: 0.001
    search_space:
      - 0.001
      - 0.0001
      - 0.00001
  lr_decay:
    default: 50
    search_space:
    - 50
  teacher_forcing_gamma:
    default: 0.95
    search_space:
    - 0.9
  conservation_constraint:
    default: 0.0
    search_space:
      - 0.0
      - 0.01
      - 0.1
epochs: 100
horizon: 40
fixed_boundary: false
force_zeros: false
use_encoder: true
context: 24
root_transformed_loss: true
enforce_conservation: false
compute_fluxes: false
boundary_constraint_only: true
perturbation_std: 0
perturbation_mean: 0
batch_size: 1
boundary_model: none
