# @package source_sink_model
_target_: fluxrgnn.models.SourceSink
static_cell_features:
  coords: ${model.coord_dim}
dynamic_cell_features: ${model.env_vars}
n_hidden: ${model.n_hidden}
use_hidden: true
n_fc_layers: 1
activation: ${model.activation}
use_log_transform: ${model.use_log_transform}
dropout_p: ${model.dropout_p}
transforms: ${model.transforms}