# @package model.radar2cell_model
_target_: fluxrgnn.models.CorrectedRadarToCellKNNInterpolation
_partial_: true
k: 10
radar_variables:
  x: 1
  bird_uv: 2
static_cell_features:
  coords: ${model.coord_dim}
dynamic_cell_features: ${model.env_vars}
n_hidden: 32 #${model.n_hidden}
n_fc_layers: 1
activation: ${model.activation}
dropout_p: ${model.dropout_p}
