# @package model.radar2cell_model
_target_: fluxrgnn.models.RadarToCellGNN
_partial_: true
k: 10
n_hidden: ${model.radar_embedding_dim}
n_fc_layers: 1
activation: ${model.activation}
dropout_p: ${model.dropout_p}
dynamic_radar_features:
  x: 1
  bird_uv: 2
static_cell_features:
  coords: ${model.coord_dim}
static_radar_features:
  coords: ${model.coord_dim}
location_encoder: ${model.location_encoder}
