# @package decoder
_target_: fluxrgnn.models.RecurrentDecoder
node_rnn: ${model.node_rnn}
n_rnn_layers: 1
n_hidden: ${model.n_hidden}
use_encoder: true
dropout_p: ${model.dropout_p}
edge_features:
  edge_attr: ${model.n_edge_attr}
dynamic_cell_features: ${model.env_vars}